apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.aiService.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.aiService.name }}
    {{- include "levatas.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.aiService.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.aiService.port }}
      targetPort: {{ .Values.aiService.port }}
      nodePort: {{ .Values.aiService.nodePort }}
