apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.reviewService.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.reviewService.name }}
    {{- include "levatas.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.reviewService.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.reviewService.port }}
      targetPort: {{ .Values.reviewService.port }}
      nodePort: {{ .Values.reviewService.nodePort }}
